### ISSUE TITLE
Translation model training

### ISSUE THREAD

**Issue by richardburleigh** [ducanhdt/openai_whisper_finetuning#1]
Really impressive work in fine-tuning Whisper!

Do you know what changes would need to be made to train the translation model instead?

**Comment by ducanhdt** [comment]
I think there are 2 things you have to change to fine-tune the translation task:
1. Modify the data loader to load the data containing source audio, source text, and target text. 
2. Change the task token from "transcribe" to "translate"
In case you want to fine-tune both tasks at the same time. It may be much more difficult but gain the performance

**Comment by ducanhdt** [comment]
@richardburleigh for this issue, you can check my code in [this commit](https://github.com/ducanhdt/openai_whisper_finetuning/commit/5409f55d2bdae3657c0973ddefaf61f27f150be1)

**Comment by richardburleigh** [comment]
Wow.. Thank you so much, this is great work!
