### ISSUE TITLE
Conflict when run on new dataset 

### ISSUE THREAD

**Issue by GoldDRoge** [ducanhdt/openai_whisper_finetuning#2]
mình có dùng một bộ dataset khác nhưng đã struct lại giống như vivos nhưng khi chạy train thì  bị lỗi này 
RuntimeError: The size of tensor a (529) must match the size of tensor b (448) at non-singleton dimension 1
không biết có phải là do max sequence lenght của mình cao hơn config model không và mình phải chỉnh lại nó ở đâu vì mình không thấy trong file config yaml có.

**Comment by ducanhdt** [comment]
hiện tại thì ở phần dataset mình chưa có phần lọc audio dài, mình cũng chưa gặp lỗi này này nên mình không chắc nhưng khi dự đoán thì model cũng chỉ dự đoán tối đa 30s thôi nên mình nghĩ bạn cần 1 bước cắt/lọc bỏ audio dài hơn 30s

**Comment by GoldDRoge** [comment]
à ra vậy cảm ơn bạn nhiều .
