### ISSUE TITLE
finetune.py - No such file or directory: '../train/songs'

### ISSUE THREAD

**Issue by drnic** [ducanhdt/openai_whisper_finetuning#6]
```
$ python finetune.py

{'learning_rate': 1e-05, 'weight_decay': 0.01, 'adam_epsilon': 1e-08, 'warmup_steps': 2, 'batch_size': 4, 'num_worker': 2, 'num_train_epochs': 5, 'gradient_accumulation_steps': 1, 'log_output_dir': 'content/logs', 'check_output_dir': 'content/artifacts', 'train_name': 'whisper', 'train_id': 'librispeech01', 'model_name': 'base', 'sample_rate': 16000, 'lang': 'vi', 'checkpoint_path': ''}
Traceback (most recent call last):
  File ".../openai_whisper_finetuning/finetune.py", line 32, in <module>
    train_dataset = ZaloAiWithTimestampTraining("train")
  File ".../openai_whisper_finetuning/dataset.py", line 250, in __init__
    song_paths_list = {i.replace(".wav","") for i in os.listdir(self.song_path) if ".wav" in i}
FileNotFoundError: [Errno 2] No such file or directory: '../train/songs'
```

<img width="545" alt="image" src="https://user-images.githubusercontent.com/108/204920794-f07a6b13-0da2-4ee1-95ef-685b7b1f49c1.png">

The google drive samples don't include `train/songs` nor `train/labels` directories:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/108/204920560-ea451ccb-953a-4d83-8565-a3b753df017c.png">

Is it possible to re-upload your training data so we can run training and see it work?

**Comment by ducanhdt** [comment]
you can download data for this contest on their website here: https://challenge.zalo.ai/portal/lyric-alignment
Do you want to fine-tune Whisper with timestamps or transcripts only? In the latter case, the vivos(vi) and librispeech(en) are possible options
