### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by zyb8543d** [ducanhdt/openai_whisper_finetuning#7]
I always  get "CUDA out of memory" error ,when train start.
I have 4 v00 gpu and  32G video memory.
I reduce batchsize to 1, it still met the error.

**Comment by ducanhdt** [comment]
hello @v-yunbin, which dataset you are using for training?

**Comment by zyb8543d** [comment]
> hello @v-yunbin, which dataset you are using for training?

my private dataset, about 1w hours.
Whether to consider reducing model parameters with lora? and similar load_model().half() from HuggingFace

**Comment by ducanhdt** [comment]
Could you share your dataset, and dataloader for your dataset.
It's a good idea, however, this repo was a small pet project during my career break and currently, I have no time to contribute more features.

**Comment by ducanhdt** [comment]
in case you only have audio and transcript I recommend you to take a look and using [this dataset module](https://github.com/ducanhdt/openai_whisper_finetuning/blob/03f3a819ee69ced572129a4b508e0a82a4000aed/dataset.py#L118)
